### PR TITLE
Hoist process watching to memory managers

### PR DESCRIPTION
**Pull request by quisquous**
As a prerequisite to implementing #106, move process watching up from FooMemory classes to FooMemoryManager classes.

### CODE REVIEW

**Comment by quisquous** [comment]
@valarnin what about this approach (example on AggroMemory, and I'll follow up with the rest if it looks good).  I think if I do this, then I can follow up with #106 and it will then only signature scan when considering a candidate.

**Comment by valarnin** [comment]
This is going to potentially run into a race condition because the underlying FFXIVMemory class relies on `repository.RegisterProcessChangedHandler` as well, and if that handler isn't triggered before the FooMemoryManager handlers, it's going to break.

**Comment by quisquous** [comment]
> This is going to potentially run into a race condition because the underlying FFXIVMemory class relies on `repository.RegisterProcessChangedHandler` as well, and if that handler isn't triggered before the FooMemoryManager handlers, it's going to break.

Sorry, I don't understand or maybe there's a misunderstanding somewhere.  `FFXIVMemory` uses `FFXIVRepository.RegisterProcessChangedHandler`.  `AggroMemoryManager` uses `FFXIVMemory.RegisterOnProcessChangeHandler`.  The `FFXIVMemory` version gets the event from the repo, which then forwards it along to all of the memory managers.

**Comment by valarnin** [comment]
That's what I get for trying to review between p8s pulls 🙃 

I think this is fine then.

**Comment by quisquous** [comment]
Ok, converted the other classes to this style.

**Review by valarnin — APPROVED** [review]
Tested the build artifact and it looks good for the normal test cases I've been using for this.

**Pull request merged**
