### PR TITLE
Dawntrail Global support version bump

### PR DESCRIPTION
**Pull request by valarnin**

### CODE REVIEW

**Review by wexxlee — APPROVED** [review]
Would it make sense to version bump to a new minor (0.20.1) instead?  I think that's a cactbot convention for new expacs, so don't know if OP necessarily does (or needs to) follow the same convention.  Either way, fine w/me.

**Comment by valarnin** [comment]
This would be 0.20.0 instead then. I don't think OP has traditionally bumped versions for expansions, but rather for significant updates. This I guess might count for both, given how much was broken by the 7.0 release. I'm open to whatever makes sense.

**Comment by wexxlee** [comment]
> This would be 0.20.0 instead then. I don't think OP has traditionally bumped versions for expansions, but rather for significant updates. This I guess might count for both, given how much was broken by the 7.0 release. I'm open to whatever makes sense.

Gotcha.  I feel the same, so feel free to merge, or renumber & merge, as you see fit!

**Comment by valarnin** [comment]
I'll merge this now as the beta update, and depending on how the `getCombatants` stuff shakes out that will probably be enough to bump to `0.20.0`.

**Pull request merged**
