### PR TITLE
Add FFXIV plugin settings to tech support button

### PR DESCRIPTION
**Pull request by quisquous**

### CODE REVIEW

**Comment by quisquous** [comment]
I'm not sure about the plumbing here, in terms of exposing the `TabPage` from the repo, but it seemed better than changing the access modifier on `GetPluginData`.

**Comment by valarnin** [comment]
Could it make more sense to read this info from the `FFXIV_ACT_Plugin.config.xml` file instead?

**Comment by quisquous** [comment]
How do you know which file is the one currently being used by the running plugin? Also, it seems like there could be some staleness there, where somebody's current settings don't match what's saved in the config file.

**Comment by valarnin** [comment]
> How do you know which file is the one currently being used by the running plugin?

```cs
Path.Combine(ActGlobals.oFormActMain.AppDataFolder.FullName, "Config", "FFXIV_ACT_Plugin.config.xml")
```

> Also, it seems like there could be some staleness there, where somebody's current settings don't match what's saved in the config file.

I had thought that it wrote the config when any option changed, but some quick testing shows that not to be the case.

Another potential option would be to invoke the `GetDataCollectionSettings` method instead on `public class SettingsPropertyPage : UserControl`, which returns `DataCollectionSettingsEventArgs`, which has `DisableCombatLog` corresponding to the hide chat log checkbox?

`SettingsPropertyPage` is registered to `FFXIV_ACT_Plugin.dll`'s IOC container.

**Comment by quisquous** [comment]
> Another potential option would be to invoke the `GetDataCollectionSettings` method instead on `public class SettingsPropertyPage : UserControl`, which returns `DataCollectionSettingsEventArgs`, which has `DisableCombatLog` corresponding to the hide chat log checkbox?
> 
> `SettingsPropertyPage` is registered to `FFXIV_ACT_Plugin.dll`'s IOC container.

Sorry to be dense, but I do not see any of these classes anywhere and so am not sure how to get from point A to point B.  I've tried searching and looking through references, but I am not sure where you are seeing this.  (For what it's worth, it's also not just about `DisableCombatLog`, but is about all settings, especially deucalion injection.)

**Comment by valarnin** [comment]
That's my bad, I was referencing an older decompile of the FFXIV_ACT_Plugin.dll file, the method name and such were changed apparently (from `DataCollectionSettings` to `MemoryScanSettings`).

Here's two ways to implement it in `FFXIVRepository.cs`. The `Direct` method requires adding references to `FFXIV_ACT_Plugin.dll` and `SDK/FFXIV_ACT_Plugin.Config.dll`.

```cs
        [MethodImpl(MethodImplOptions.NoInlining)]
        internal Dictionary<string, object> GetFFXIVPluginConfigReflection()
        {
            var plugin = GetPluginData();
            if (plugin == null) return null;
            var field = plugin.pluginObj.GetType().GetField("_iocContainer", BindingFlags.NonPublic | BindingFlags.Instance);
            if (field == null)
            {
                logger.Log(LogLevel.Error, "Unable to retrieve _iocContainer field information from FFXIV_ACT_Plugin");
                return null;
            }
            var iocContainer = field.GetValue(plugin.pluginObj);
            if (iocContainer == null)
            {
                logger.Log(LogLevel.Error, "Unable to retrieve _iocContainer field value from FFXIV_ACT_Plugin");
                return null;
            }
            var getServiceMethod = iocContainer.GetType().GetMethod("GetService");
            if (getServiceMethod == null)
            {
                logger.Log(LogLevel.Error, "Unable to retrieve _iocContainer field value from FFXIV_ACT_Plugin");
                return null;
            }
            var pluginAssembly = AppDomain.CurrentDomain.GetAssemblies().
                SingleOrDefault(assembly => assembly.GetName().Name == "FFXIV_ACT_Plugin");
            if (pluginAssembly == null)
            {
                logger.Log(LogLevel.Error, "Unable to retrieve FFXIV_ACT_Plugin assembly");
                return null;
            }
            var settingsPage = getServiceMethod.Invoke(iocContainer, new object[] { pluginAssembly.GetType("FFXIV_ACT_Plugin.SettingsPropertyPage") });
            if (settingsPage == null)
            {
                logger.Log(LogLevel.Error, "Unable to retrieve SettingsPropertyPage singleton from FFXIV_ACT_Plugin IOC");
                return null;
            }
            var memoryScanSettingsMethod = settingsPage.GetType().GetMethod("GetMemoryScanSettings");
            if (memoryScanSettingsMethod == null)
            {
                logger.Log(LogLevel.Error, "Unable to retrieve GetMemoryScanSettings method signature from SettingsPropertyPage singleton");
                return null;
            }
            var memoryScanSettings = memoryScanSettingsMethod.Invoke(settingsPage, new object[]{ });
            if (memoryScanSettings == null)
            {
                logger.Log(LogLevel.Error, "Unable to retrieve GetMemoryScanSettings value from SettingsPropertyPage singleton");
                return null;
            }
            var parseSettingsMethod = settingsPage.GetType().GetMethod("GetParseSettings");
            if (parseSettingsMethod == null)
            {
                logger.Log(LogLevel.Error, "Unable to retrieve GetParseSettings method signature from SettingsPropertyPage singleton");
                return null;
            }
            var parseSettings = parseSettingsMethod.Invoke(settingsPage, new object[] { });
            if (parseSettings == null)
            {
                logger.Log(LogLevel.Error, "Unable to retrieve GetParseSettings value from SettingsPropertyPage singleton");
                return null;
            }
            var settings = new Dictionary<string, object>();
            foreach (var fi in memoryScanSettings.GetType().GetFields())
            {
                settings.Add(fi.Name, fi.GetValue(memoryScanSettings));
            }
            foreach (var fi in parseSettings.GetType().GetFields())
            {
                settings.Add(fi.Name, fi.GetValue(parseSettings));
            }
            return settings;
        }
```
```cs
        [MethodImpl(MethodImplOptions.NoInlining)]
        internal Dictionary<string, object> GetFFXIVPluginConfigDirect()
        {
            var plugin = GetPluginData();
            if (plugin == null) return null;
            var field = plugin.pluginObj.GetType().GetField("_iocContainer", BindingFlags.NonPublic | BindingFlags.Instance);
            if (field == null)
            {
                logger.Log(LogLevel.Error, "Unable to retrieve _iocContainer field information from FFXIV_ACT_Plugin");
                return null;
            }
            var iocContainer = field.GetValue(plugin.pluginObj);
            if (iocContainer == null)
            {
                logger.Log(LogLevel.Error, "Unable to retrieve _iocContainer field value from FFXIV_ACT_Plugin");
                return null;
            }
            var getServiceMethod = iocContainer.GetType().GetMethod("GetService");
            if (getServiceMethod == null)
            {
                logger.Log(LogLevel.Error, "Unable to retrieve _iocContainer field value from FFXIV_ACT_Plugin");
                return null;
            }
            var pluginAssembly = AppDomain.CurrentDomain.GetAssemblies().
                SingleOrDefault(assembly => assembly.GetName().Name == "FFXIV_ACT_Plugin");
            if (pluginAssembly == null)
            {
                logger.Log(LogLevel.Error, "Unable to retrieve FFXIV_ACT_Plugin assembly");
                return null;
            }
            FFXIV_ACT_Plugin.SettingsPropertyPage settingsPage = (FFXIV_ACT_Plugin.SettingsPropertyPage) getServiceMethod
                .Invoke(iocContainer, new object[] { pluginAssembly.GetType("FFXIV_ACT_Plugin.SettingsPropertyPage") });
            if (settingsPage == null)
            {
                logger.Log(LogLevel.Error, "Unable to retrieve SettingsPropertyPage singleton from FFXIV_ACT_Plugin IOC");
                return null;
            }
            var memoryScanSettings = settingsPage.GetMemoryScanSettings();
            if (memoryScanSettings == null)
            {
                logger.Log(LogLevel.Error, "Unable to retrieve GetMemoryScanSettings value from SettingsPropertyPage singleton");
                return null;
            }
            var parseSettings = settingsPage.GetParseSettings();
            if (parseSettings == null)
            {
                logger.Log(LogLevel.Error, "Unable to retrieve GetParseSettings value from SettingsPropertyPage singleton");
                return null;
            }
            var settings = new Dictionary<string, object>();
            foreach (var fi in memoryScanSettings.GetType().GetFields())
            {
                settings.Add(fi.Name, fi.GetValue(memoryScanSettings));
            }
            foreach (var fi in parseSettings.GetType().GetFields())
            {
                settings.Add(fi.Name, fi.GetValue(parseSettings));
            }
            return settings;
        }
```

Here's the definition of the two settings classes:

```cs
    public class MemoryScanSettings : EventArgs
    {
        public int ProcessID;
        public string LogFileFolder;
        public bool DisableNetworkScan;
        public bool EnableScanHPPercent;
        public bool LogAllNetworkData;
        public bool DisableCombatLog;
        public string NetworkIP;
        public bool UseWinPCap;
        public bool UseSocketFilter;
    }

    public class ParseSettings : EventArgs
    {
        public bool DisableDamageShield;
        public bool DisableCombinePets;
        public bool GraphPotency;
        public int LanguageID;
        public ParseFilterMode ParseFilter;
        public bool DisableNetworkScan;
        public bool SimulateIndividualDoTCrits;
        public bool ShowRealDoTTicks;
        public bool ParsePotency;
        public bool ShowDebug;
    }
```

Deucalion is probably on `ParseSettings` but you'll need to bump to the latest SDK version to get it I think, which is probably a good reason to use the `Reflection` version of the method to avoid version issues with CN/KO plugin versions.

**Comment by quisquous** [comment]
Ohhhhhhh this is all from decompilation and reflection.  No wonder I couldn't find it.  This seems like a lot of digging into unexposed internals.  What do you think about landing this existing patch and asking Ravahn to expose these settings publicly?

**Comment by quisquous** [comment]
> This runs into the same issue of adding references to those two DLL files which will likely break compatibility with CN/KO clients.

Yeah, this seems like a blocker to me.

Techno requested that the settings were sorted, and so I ended up switching this code to be based on the checkbox `Name` rather than its text.  I think that's going to be slightly more reliable than matching the text itself, and should work even if this is ever translated into other languages (maybe the Chinese version does this?).

I think that's "good enough" for me for now.  If we have to do reflection and try/catch on all the names anyway, then that loose coupling is just as good as having a list of string checkbox names.

**Pull request merged**
