### PR TITLE
make `tools/fetch_deps.py` generate same output in different os

### LINKED ISSUE #24: Running `tools/fetch_deps.py` under a bash environment breaks FFXIV SDK
```bash
ls Thirdparty/FFXIV_ACT_Plugin 
 FFXIV_ACT_Plugin.dll         'SDK\FFXIV_ACT_Plugin.Common.dll'  'SDK\FFXIV_ACT_Plugin.LogFile.dll'  'SDK\FFXIV_ACT_Plugin.Network.dll'  'SDK\FFXIV_ACT_Plugin.Parse.dll'
 FFXIV_ACT_Plugin_Korean.dll  'SDK\FFXIV_ACT_Plugin.Config.dll'  'SDK\FFXIV_ACT_Plugin.Memory.dll'   'SDK\FFXIV_ACT_Plugin.Overlay.dll'  'SDK\FFXIV_ACT_Plugin.Resource.dll'
```

image

### PR DESCRIPTION
**Pull request by trim21**
currently update hashes will generate DEPS.py with `crlf` EOL on windows, this pr make sure it always generate lf eol, same with committed file.

should also fix #24 , caused by different path separator

### CODE REVIEW

**Comment by trim21** [comment]
@valarnin can you try?

**Comment by trim21** [comment]
and why we are using curl to download curl in `fetch_deps.py` ?

**Comment by valarnin** [comment]
This is still not working as expected.

```
$ rm -rf Thirdparty/FFXIV_ACT_Plugin
$ python tools/fetch_deps.py        
Fetching missing or outdated dependencies...
[  1/  1]: FFXIV_ACT_Plugin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2804k  100 2804k    0     0  2646k      0  0:00:01  0:00:01 --:--:-- 2646k
Hashing...
Extracting...
Saving dependency cache...
Cleaning up...
$ ls Thirdparty/FFXIV_ACT_Plugin    
 FFXIV_ACT_Plugin.dll         'SDK\FFXIV_ACT_Plugin.Common.dll'  'SDK\FFXIV_ACT_Plugin.LogFile.dll'  'SDK\FFXIV_ACT_Plugin.Network.dll'  'SDK\FFXIV_ACT_Plugin.Parse.dll'
 FFXIV_ACT_Plugin_Korean.dll  'SDK\FFXIV_ACT_Plugin.Config.dll'  'SDK\FFXIV_ACT_Plugin.Memory.dll'   'SDK\FFXIV_ACT_Plugin.Overlay.dll'  'SDK\FFXIV_ACT_Plugin.Resource.dll'
```

**Comment by trim21** [comment]
@valarnin should works fine now

```text
$ tree Thirdparty/FFXIV_ACT_Plugin/
Thirdparty/FFXIV_ACT_Plugin/
├── FFXIV_ACT_Plugin.dll
├── FFXIV_ACT_Plugin_Korean.dll
└── SDK
    ├── FFXIV_ACT_Plugin.Common.dll
    ├── FFXIV_ACT_Plugin.Config.dll
    ├── FFXIV_ACT_Plugin.LogFile.dll
    ├── FFXIV_ACT_Plugin.Memory.dll
    ├── FFXIV_ACT_Plugin.Network.dll
    ├── FFXIV_ACT_Plugin.Overlay.dll
    ├── FFXIV_ACT_Plugin.Parse.dll
    └── FFXIV_ACT_Plugin.Resource.dll

1 directory, 10 files
```

**Review by valarnin — APPROVED** [review]
Works for me as expected now.

**Pull request merged**
