### PR TITLE
Update opcodes for Global 7.1

### PR DESCRIPTION
**Pull request by Makar8000**
Used [OpcodeExtractor](https://github.com/OverlayPlugin/OpcodeExtractor) for this since my old method has been broken since 7.0

### CODE REVIEW

**Review by valarnin — APPROVED** [review]
Going to pre-approve this, but can't actually check the opcodes myself until tomorrow sometime. If someone else can verify that these are correct (tested in-game), feel free to merge.

**Comment by Makar8000** [comment]
Considering the generated opcodes used by the parser plugin are all different from what Flawed provided on the ACT discord, there is a good chance these are wrong. I may not be available tomorrow for testing, but feel free to open a new PR if this is the case.

**Comment by Makar8000** [comment]
Checked most of them and it looks good. Someone will have to check into OpcodeExtractor and update it accordingly (I'm guessing it's just offsets)

**Comment by valarnin** [comment]
Yeah, it's offsets. I have the correct offsets now, I'll fix opcode extractor in a bit. These opcodes all look correct to me.

**Pull request merged**
