### PR TITLE
Bump version to 0.19.19

### PR DESCRIPTION
**Pull request by quisquous**

### CODE REVIEW

**Comment by quisquous** [comment]
Please merge after approval.  Mostly wanted to get the combatant lines out there for other folks to use.

**Comment by valarnin** [comment]
Before I merge, has anyone else done any extensive testing with combatant lines? I didn't see much feedback on others using them in the original PR for them,

I don't want to merge this and push them out if they're too excessive for normal hardware or something.

**Comment by Legends0** [comment]
> Before I merge, has anyone else done any extensive testing with combatant lines? I didn't see much feedback on others using them in the original PR for them,

I have used the log lines that quisquos provided me in testing timing triggers for cactbot. Could it be possible this is be set default to off but an option to turn it on for testing timing of delay needed for cactbot's use in triggers?

**Comment by quisquous** [comment]
I've been using this PR for a while now and haven't noticed any difference. But, I think this comes back to our previous discussion of "what's too much cpu", which is a hard question to answer.

**Comment by valarnin** [comment]
It's also a question of disk I/O. I don't have any spinning rust around to see if that would bottleneck due to the extra I/O, for example, and I didn't crunch the numbers on if the amount of data being added by those lines would cause issues with actual HDDs.

**Comment by quisquous** [comment]
Yeah, I don't mean to push a release before it's ready. I guess my question for you is...how would you determine if this was enough? Or, what path would you like to follow?

(a) do the release, and we can turn off the lines / make them optional if there's complaints? (although as always, how to measure this in the field)
(b) make them optional now and ask people to beta test; turn them on always later
(c) ask people to beta test manually (maybe techno, since they're running a win7 potato it sounds like)
(d) something else?

**Comment by valarnin** [comment]
I think preferably we'd get someone with lower-end hardware to test the artifacts attached to this PR? Preferably in something like a 24-man instance.

But I'm not sure if we have anyone we can call on to test that case. Maybe @MyTechnoHunter if their hardware is low-end enough?

If we can't find someone to test in the next couple hours I guess we can just push it out now, or make them optional as you outlined above.

**Comment by quisquous** [comment]
Ah no, there's not so much urgency as "in the next couple of hours".  I thought this would be convenient for @Legends0 if we did a release, but it can wait too.

@Legends0 can manually apply the artifact from https://github.com/OverlayPlugin/OverlayPlugin/actions/runs/4835074081?pr=208 too if they want to use this now

**Review by valarnin — APPROVED** [review]
I think we merge this now and get some feedback before the next raid tier drops, so if we need to revert we can do so ahead of time.

**Pull request merged**
