### PR TITLE
Added getVersion call

### PR DESCRIPTION
**Pull request by xpdota**
Add a simple call to retrieve the OP version.

### CODE REVIEW

**Comment by xpdota** [comment]
The extra junk on the diff seems to be CR-LFs getting replaced with LFs to match the rest of the file. I can break that into a separate PR if needed, but it seems the windows git client forces them back to the correct line endings no matter what I do (even though they aren't my lines).

**Comment by quisquous** [comment]
Yeah, you shouldn't change whitespace in a PR unnecessarily, in my opinion.  Can you undo those?

**Comment by xpdota** [comment]
I'm just going to fix it in a separate PR, otherwise I have to chunk/patch commit everything.

**Comment by quisquous** [comment]
> I'm just going to fix it in a separate PR, otherwise I have to chunk/patch commit everything.

It's one (1) chunk and ten lines of code.

I filed #87 for line endings.

**Comment by xpdota** [comment]
This one is fixed

**Review by quisquous — APPROVED** [review]

**Pull request merged**
