### PR TITLE
Update opcodes for Global 6.58

### PR DESCRIPTION
**Pull request by Makar8000**

### CODE REVIEW

**Review by valarnin — APPROVED** [review]
No issues getting the new opcodes, I take it?

**Review by MaikoTan — APPROVED** [review]
GJ !

**Comment by valarnin** [comment]
Given that the `FFXIV_ACT_Plugin` beta is posted, I'm going to go ahead and merge this.

**Comment by Makar8000** [comment]
> No issues getting the new opcodes, I take it?

No issues. I noticed new opcodes were added to this repo a few days ago, so I prepared/tested against an old exe to make sure things were working prior to this patch 👍

**Pull request merged**
