### PR TITLE
Added TransformationId field to Combatant.

### PR DESCRIPTION
**Pull request by xpdota**
This should allow triggers to be made for the M/F in/out P2 TOP mechanic.

### CODE REVIEW

**Comment by quisquous** [comment]
Is there any easy way to find this in the future in some other content, if the offset changes?

**Review by quisquous — APPROVED** [review]

**Comment by quisquous** [comment]
ALSO, thank you for tracking this down.  This'll be great.

**Comment by xpdota** [comment]
The offset is copied from FFXIVClientStructs, so if it does change, you should be able to just yank the new offset. Or if those become auto-gen'd at some point, problem solved.

**Comment by quisquous** [comment]
Oh!! For some reason I had looked there, but didn't see it (or know what it was called).  That's perfect.

**Pull request merged**
