### PR TITLE
Add CE Director log line

### PR DESCRIPTION
**Pull request by valarnin**
Still WIP, need the version string for KO/CN clients to add opcode entries for those versions. Also, same as the Fate PR, only the commits starting with `Add CEDirector log line` are relevant, as this depends on groundwork laid by #51.

### CODE REVIEW

**Comment by valarnin** [comment]
Rebased to main.

I'm not sure if there are any CN or KO client users that can provide the required version string?

**Comment by ShadyWhite** [comment]
> Rebased to main.
> 
> I'm not sure if there are any CN or KO client users that can provide the required version string?

For CN client, the version string is "2022.08.20.0000.0000". Is there anything else I can provide?

**Comment by valarnin** [comment]
> Is there anything else I can provide?

Nope, that's all I needed.

**Comment by Bing-su** [comment]
`2022.07.05.0000.0000` (6.05)

**Comment by valarnin** [comment]
Roughly 5 minutes of CE lines, for reference for how often they occur.

[CE Lines.log](https://github.com/OverlayPlugin/OverlayPlugin/files/9594922/CE.Lines.log)

**Review by quisquous — APPROVED** [review]

**Pull request merged**
