### PR TITLE
Migrate to SDK project format

### PR DESCRIPTION
**Pull request by valarnin**
This is an alternative to #82, as it appears that marzent hasn't had time to update their PR and address outstanding concerns/issues.

This PR results in an almost-identical build output folder (`out/Debug`, `out/Release`) and an almost identical zip/7z artifact, compared to the current build/release process. The only added files appear to be `*.resources.dll` files for some projects that should probably have been built and included to begin with, but were missing the references to trigger those builds, as well as some `System.*` dll files which are required due to the way `dotnet` builds as opposed to the way `msbuild` builds and compiles.

This also takes the step of pulling common csproj settings to a parent file, `Directory.Build.props`, so that things like updating version number are easier and less error prone.

List of added files, when compared to the most recent release zip. I have confirmed that all `System.*` dll files are targeting .NET Framework 4.0, and that there is no conflict with loading across a couple environments.

```
OverlayPlugin/de-DE/HtmlRenderer.resources.dll
OverlayPlugin/de-DE/OverlayPlugin.Core.resources.dll
OverlayPlugin/de-DE/OverlayPlugin.Updater.resources.dll

OverlayPlugin/fr-FR/HtmlRenderer.resources.dll
OverlayPlugin/fr-FR/OverlayPlugin.Core.resources.dll
OverlayPlugin/fr-FR/OverlayPlugin.Updater.resources.dll

OverlayPlugin/ja-JP/HtmlRenderer.resources.dll
OverlayPlugin/ja-JP/OverlayPlugin.Core.resources.dll
OverlayPlugin/ja-JP/OverlayPlugin.Updater.resources.dll

OverlayPlugin/ko-KR/HtmlRenderer.resources.dll
OverlayPlugin/ko-KR/OverlayPlugin.Core.resources.dll
OverlayPlugin/ko-KR/OverlayPlugin.Updater.resources.dll

OverlayPlugin/zh-CN/HtmlRenderer.resources.dll
OverlayPlugin/zh-CN/OverlayPlugin.Core.resources.dll
OverlayPlugin/zh-CN/OverlayPlugin.Updater.resources.dll

OverlayPlugin/libs/System.Buffers.dll
OverlayPlugin/libs/System.Memory.dll
OverlayPlugin/libs/System.Numerics.Vectors.dll
OverlayPlugin/libs/System.Resources.Extensions.dll
OverlayPlugin/libs/System.Runtime.CompilerServices.Unsafe.dll
```

Anything that was invoking the stopwatch code has been switched to use `#if TRACEPERF` instead, due to `TRACE` being extremely annoying to properly undefine in SDK-style projects built with `dotnet`.

This could use some additional testing (namely testing the actual built artifact by simulating the update process and testing in other languages), but I wanted to throw it up here for initial feedback.

The only outstanding issue I'm aware of is that the new build process includes the full version, `0.19.23.0`, whereas the old build process left off the last segment, `0.19.23`. This means that merging this PR will result in a new build/release of OverlayPlugin despite not being intended to. There are a few ways to handle this but I'm not sure which is the better option:
1. Drop the last segment entirely. I'm not sure if we've ever really used it anyways, and I'm pretty sure .NET doesn't care if there are three or four segments. Additionally we could always add it back if needed?
2. Conditionally trim the last segment if it's `.0`
3. Manually move or duplicate the existing tag for `0.19.23` to `0.19.23.0`, to prevent the automatic release logic

### CODE REVIEW

**Comment by quisquous** [comment]
Visual Studio gives me a bunch of "configuration errors" and asks me to open the configuration manager to fix them. (This is the mapping in the sln file.) Without fixing it, building Release x64 only builds the helper strip client structs executable and nothing else. Once I open the configuration manager, it does these automatic edits, which seem to fix it:

```diff
                {E2BC6483-B966-4A4A-B4CC-D50A4BD73AF3}.Debug|x64.Build.0 = Debug|x64
                {E2BC6483-B966-4A4A-B4CC-D50A4BD73AF3}.Debug|x64.Build.0 = Debug|x64
                {E2BC6483-B966-4A4A-B4CC-D50A4BD73AF3}.Release|Any CPU.ActiveCfg = Release|Any CPU
                {E2BC6483-B966-4A4A-B4CC-D50A4BD73AF3}.Release|Any CPU.Build.0 = Release|Any CPU
-               {E2BC6483-B966-4A4A-B4CC-D50A4BD73AF3}.Release|x64.ActiveCfg = Release|x64
-               {E2BC6483-B966-4A4A-B4CC-D50A4BD73AF3}.Release|x64.Build.0 = Release|x64
+               {E2BC6483-B966-4A4A-B4CC-D50A4BD73AF3}.Release|x64.ActiveCfg = Release|Any CPU^M
+               {E2BC6483-B966-4A4A-B4CC-D50A4BD73AF3}.Release|x64.Build.0 = Release|Any CPU^M
                {B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
                {B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Debug|Any CPU.Build.0 = Debug|Any CPU
                {B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Debug|x64.ActiveCfg = Debug|x64
                {B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Debug|x64.Build.0 = Debug|x64
                {B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Release|Any CPU.ActiveCfg = Release|Any CPU
                {B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Release|Any CPU.Build.0 = Release|Any CPU
-               {B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Release|x64.ActiveCfg = Release|x64
-               {B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Release|x64.Build.0 = Release|x64
+               {B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Release|x64.ActiveCfg = Release|Any CPU^M
+               {B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Release|x64.Build.0 = Release|Any CPU^M
                {423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
                {423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Debug|Any CPU.Build.0 = Debug|Any CPU
                {423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Debug|x64.ActiveCfg = Debug|x64
                {423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Debug|x64.Build.0 = Debug|x64
                {423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Release|Any CPU.ActiveCfg = Release|Any CPU
                {423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Release|Any CPU.Build.0 = Release|Any CPU
-               {423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Release|x64.ActiveCfg = Release|x64
-               {423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Release|x64.Build.0 = Release|x64
+               {423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Release|x64.ActiveCfg = Release|Any CPU^M
+               {423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Release|x64.Build.0 = Release|Any CPU^M
                {5D15AD79-050C-4780-986E-0F1138EA1D40}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
                {5D15AD79-050C-4780-986E-0F1138EA1D40}.Debug|Any CPU.Build.0 = Debug|Any CPU
                {5D15AD79-050C-4780-986E-0F1138EA1D40}.Debug|x64.ActiveCfg = Debug|x64
                {5D15AD79-050C-4780-986E-0F1138EA1D40}.Debug|x64.Build.0 = Debug|x64
                {5D15AD79-050C-4780-986E-0F1138EA1D40}.Release|Any CPU.ActiveCfg = Release|Any CPU
                {5D15AD79-050C-4780-986E-0F1138EA1D40}.Release|Any CPU.Build.0 = Release|Any CPU
-               {5D15AD79-050C-4780-986E-0F1138EA1D40}.Release|x64.ActiveCfg = Release|x64
-               {5D15AD79-050C-4780-986E-0F1138EA1D40}.Release|x64.Build.0 = Release|x64
+               {5D15AD79-050C-4780-986E-0F1138EA1D40}.Release|x64.ActiveCfg = Release|Any CPU^M
+               {5D15AD79-050C-4780-986E-0F1138EA1D40}.Release|x64.Build.0 = Release|Any CPU^M
                {82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
                {82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Debug|Any CPU.Build.0 = Debug|Any CPU
                {82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Debug|x64.ActiveCfg = Debug|x64
                {82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Debug|x64.Build.0 = Debug|x64
                {82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Release|Any CPU.ActiveCfg = Release|Any CPU
                {82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Release|Any CPU.Build.0 = Release|Any CPU
-               {82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Release|x64.ActiveCfg = Release|x64
-               {82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Release|x64.Build.0 = Release|x64
+               {82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Release|x64.ActiveCfg = Release|Any CPU^M
+               {82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Release|x64.Build.0 = Release|Any CPU^M
                {F826ED1A-187A-484F-ABE4-D794E5CE0F50}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
                {F826ED1A-187A-484F-ABE4-D794E5CE0F50}.Debug|Any CPU.Build.0 = Debug|Any CPU
                {F826ED1A-187A-484F-ABE4-D794E5CE0F50}.Debug|x64.ActiveCfg = Debug|x64
@@ -93,7 +93,7 @@ Global
                {F826ED1A-187A-484F-ABE4-D794E5CE0F50}.Release|Any CPU.ActiveCfg = Release|Any CPU
                {F826ED1A-187A-484F-ABE4-D794E5CE0F50}.Release|Any CPU.Build.0 = Release|Any CPU
                {F826ED1A-187A-484F-ABE4-D794E5CE0F50}.Release|x64.ActiveCfg = Release|Any CPU
-               {F826ED1A-187A-484F-ABE4-D794E5CE0F50}.Release|x64.Build.0 = Release|x64
+               {F826ED1A-187A-484F-ABE4-D794E5CE0F50}.Release|x64.Build.0 = Release|Any CPU^M
```

**Comment by quisquous** [comment]
> The only outstanding issue I'm aware of is that the new build process includes the full version, `0.19.23.0`, whereas the old build process left off the last segment, `0.19.23`. This means that merging this PR will result in a new build/release of OverlayPlugin despite not being intended to. There are a few ways to handle this but I'm not sure which is the better option:
> 
> 1. Drop the last segment entirely. I'm not sure if we've ever really used it anyways, and I'm pretty sure .NET doesn't care if there are three or four segments. Additionally we could always add it back if needed?
> 2. Conditionally trim the last segment if it's `.0`
> 3. Manually move or duplicate the existing tag for `0.19.23` to `0.19.23.0`, to prevent the automatic release logic

I personally think we should just continue to drop it. If we're not planning to use it, then there's no need to add inconsistency into what versions mean.

**Comment by valarnin** [comment]
> Visual Studio gives me a bunch of "configuration errors" and asks me to open the configuration manager to fix them.

Pretty sure I fixed that and it didn't get saved properly, because of annoying delays in WSL change detection (I use VSCode via WSL for actual git commit/push). I'll get that fixed tomorrow, I don't have any more time tonight to handle it.

> I personally think we should just continue to drop it. If we're not planning to use it, then there's no need to add inconsistency into what versions mean.
👍

**Comment by quisquous** [comment]
> > Visual Studio gives me a bunch of "configuration errors" and asks me to open the configuration manager to fix them.
> 
> Pretty sure I fixed that and it didn't get saved properly, because of annoying delays in WSL change detection (I use VSCode via WSL for actual git commit/push). I'll get that fixed tomorrow, I don't have any more time tonight to handle it.

Yeah, no hurry. Just FYI.

Ok, got around to building and I get a zillion errors (screenshot sorry, but you don't need 1987 errors, but here's the first few. Sorry if I'm holding it wrong, but do you know if I'm missing something obvious? I did fetch deps, at least.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0229	Ambiguity between 'CustomizeData.Count' and 'CustomizeData.Count'	OverlayPlugin.Core	C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Global\FFXIVClientStructs\FFXIV\Client\Game\Character\DrawDataContainer.cs	65	Active
Error	CS0229	Ambiguity between 'CustomizeData.Count' and 'CustomizeData.Count'	OverlayPlugin.Core	C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Global\FFXIVClientStructs\FFXIV\Client\Game\Character\DrawDataContainer.cs	70	Active
Error	CS0104	'Vector3' is an ambiguous reference between 'FFXIVClientStructs.Global.FFXIV.Client.Graphics.Vector3' and 'System.Numerics.Vector3'	OverlayPlugin.Core	C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Global\FFXIVClientStructs\FFXIV\Client\Game\Fate\FateContext.cs	26	Active
Error	CS0260	Missing partial modifier on declaration of type 'Hate'; another partial declaration of this type exists	OverlayPlugin.Core	C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Global\FFXIVClientStructs\FFXIV\Client\Game\UI\Hate.cs	9	Active
Error	CS0260	Missing partial modifier on declaration of type 'Hater'; another partial declaration of this type exists	OverlayPlugin.Core	C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Global\FFXIVClientStructs\FFXIV\Client\Game\UI\Hater.cs	9	Active
Error	CS0104	'Vector3' is an ambiguous reference between 'FFXIVClientStructs.Global.FFXIV.Client.Graphics.Vector3' and 'System.Numerics.Vector3'	OverlayPlugin.Core	C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Global\FFXIVClientStructs\FFXIV\Client\Game\UI\MarkingController.cs	25	Active
Error	CS0260	Missing partial modifier on declaration of type 'Manager'; another partial declaration of this type exists	OverlayPlugin.Core	C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Global\FFXIVClientStructs\FFXIV\Client\Graphics\Render\Manager.cs	11	Active
Error	CS0260	Missing partial modifier on declaration of type 'PartialSkeleton'; another partial declaration of this type exists	OverlayPlugin.Core	C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Global\FFXIVClientStructs\FFXIV\Client\Graphics\Render\PartialSkeleton.cs	11	Active
Error	CS0260	Missing partial modifier on declaration of type 'View'; another partial declaration of this type exists	OverlayPlugin.Core	C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Global\FFXIVClientStructs\FFXIV\Client\Graphics\Render\View.cs	8	Active
Error	CS0260	Missing partial modifier on declaration of type 'Camera'; another partial declaration of this type exists	OverlayPlugin.Core	C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Global\FFXIVClientStructs\FFXIV\Client\Graphics\Scene\Camera.cs	7	Active
Error	CS0260	Missing partial modifier on declaration of type 'ResourceGraph'; another partial declaration of this type exists	OverlayPlugin.Core	C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Global\FFXIVClientStructs\FFXIV\Client\System\Resource\ResourceGraph.cs	31	Active
Error	CS0260	Missing partial modifier on declaration of type 'CategoryContainer'; another partial declaration of this type exists	OverlayPlugin.Core	C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Global\FFXIVClientStructs\FFXIV\Client\System\Resource\ResourceGraph.cs	34	Active
Error	CS0229	Ambiguity between 'AddonPartyList.PartyListMemberStruct.Size' and 'AddonPartyList.PartyListMemberStruct.Size'	OverlayPlugin.Core	C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Global\FFXIVClientStructs\FFXIV\Client\UI\AddonPartyList.cs	46	Active
Error	CS0229	Ambiguity between 'AddonPartyList.PartyListMemberStruct.Size' and 'AddonPartyList.PartyListMemberStruct.Size'	OverlayPlugin.Core	C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Global\FFXIVClientStructs\FFXIV\Client\UI\AddonPartyList.cs	49	Active
Error	CS0229	Ambiguity between 'AddonPartyList.PartyListMemberStruct.Size' and 'AddonPartyList.PartyListMemberStruct.Size'	OverlayPlugin.Core	C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Global\FFXIVClientStructs\FFXIV\Client\UI\AddonPartyList.cs	52	Active
Error	CS0229	Ambiguity between 'AddonPartyList.PartyListMemberStruct.Size' and 'AddonPartyList.PartyListMemberStruct.Size'	OverlayPlugin.Core	C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Global\FFXIVClientStructs\FFXIV\Client\UI\AddonPartyList.cs	55	Active
```

**Comment by valarnin** [comment]
Those paths look like they're from a pretty old `FFXIVClientStructs` build,
the correct paths should be at
`OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Base\Global...` and
`OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Transformed\Global...`

You might want to double check that folder structure?

**Comment by valarnin** [comment]
For reference, the `FFXIVClientStructs` output directory changed as part of #180.
This wasn't causing an issue before because the include path for `.cs` files were explicitly defined, but with the new project structure all `.cs` files are included by default and need to be explicitly excluded:
https://github.com/OverlayPlugin/OverlayPlugin/blob/c63c01cb2cb0f8d6b96336df32435ef93da5851d/OverlayPlugin.Core/OverlayPlugin.Core.csproj#L112-L115

**Comment by quisquous** [comment]
Solution changes were not enough. I needed these additional changes to have Visual Studio stop complaining. (This is mostly the same as my previous diff, but not entirely.)

```diff
diff --git a/OverlayPlugin.sln b/OverlayPlugin.sln
index 16d8d06..a9cb76a 100644
--- a/OverlayPlugin.sln
+++ b/OverlayPlugin.sln
@@ -44,48 +44,48 @@ Global
 		{DD6D2A9A-4AD4-47B8-A1D0-C8608EA37092}.Debug|x64.Build.0 = Debug|Any CPU
 		{DD6D2A9A-4AD4-47B8-A1D0-C8608EA37092}.Release|Any CPU.ActiveCfg = Release|Any CPU
 		{DD6D2A9A-4AD4-47B8-A1D0-C8608EA37092}.Release|Any CPU.Build.0 = Release|Any CPU
-		{DD6D2A9A-4AD4-47B8-A1D0-C8608EA37092}.Release|x64.ActiveCfg = Release|x64
-		{DD6D2A9A-4AD4-47B8-A1D0-C8608EA37092}.Release|x64.Build.0 = Release|x64
+		{DD6D2A9A-4AD4-47B8-A1D0-C8608EA37092}.Release|x64.ActiveCfg = Release|Any CPU
+		{DD6D2A9A-4AD4-47B8-A1D0-C8608EA37092}.Release|x64.Build.0 = Release|Any CPU
 		{E2BC6483-B966-4A4A-B4CC-D50A4BD73AF3}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
 		{E2BC6483-B966-4A4A-B4CC-D50A4BD73AF3}.Debug|Any CPU.Build.0 = Debug|Any CPU
 		{E2BC6483-B966-4A4A-B4CC-D50A4BD73AF3}.Debug|x64.ActiveCfg = Debug|Any CPU
 		{E2BC6483-B966-4A4A-B4CC-D50A4BD73AF3}.Debug|x64.Build.0 = Debug|Any CPU
 		{E2BC6483-B966-4A4A-B4CC-D50A4BD73AF3}.Release|Any CPU.ActiveCfg = Release|Any CPU
 		{E2BC6483-B966-4A4A-B4CC-D50A4BD73AF3}.Release|Any CPU.Build.0 = Release|Any CPU
-		{E2BC6483-B966-4A4A-B4CC-D50A4BD73AF3}.Release|x64.ActiveCfg = Release|x64
-		{E2BC6483-B966-4A4A-B4CC-D50A4BD73AF3}.Release|x64.Build.0 = Release|x64
+		{E2BC6483-B966-4A4A-B4CC-D50A4BD73AF3}.Release|x64.ActiveCfg = Release|Any CPU
+		{E2BC6483-B966-4A4A-B4CC-D50A4BD73AF3}.Release|x64.Build.0 = Release|Any CPU
 		{B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
 		{B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Debug|Any CPU.Build.0 = Debug|Any CPU
 		{B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Debug|x64.ActiveCfg = Debug|Any CPU
 		{B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Debug|x64.Build.0 = Debug|Any CPU
 		{B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Release|Any CPU.ActiveCfg = Release|Any CPU
 		{B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Release|Any CPU.Build.0 = Release|Any CPU
-		{B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Release|x64.ActiveCfg = Release|x64
-		{B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Release|x64.Build.0 = Release|x64
+		{B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Release|x64.ActiveCfg = Release|Any CPU
+		{B9BBE478-8FD7-43D9-BD50-C806B1EC672F}.Release|x64.Build.0 = Release|Any CPU
 		{423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
 		{423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Debug|Any CPU.Build.0 = Debug|Any CPU
 		{423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Debug|x64.ActiveCfg = Debug|Any CPU
 		{423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Debug|x64.Build.0 = Debug|Any CPU
 		{423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Release|Any CPU.ActiveCfg = Release|Any CPU
 		{423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Release|Any CPU.Build.0 = Release|Any CPU
-		{423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Release|x64.ActiveCfg = Release|x64
-		{423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Release|x64.Build.0 = Release|x64
+		{423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Release|x64.ActiveCfg = Release|Any CPU
+		{423FCBFC-DD3B-415F-BE29-7A4A46614B79}.Release|x64.Build.0 = Release|Any CPU
 		{5D15AD79-050C-4780-986E-0F1138EA1D40}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
 		{5D15AD79-050C-4780-986E-0F1138EA1D40}.Debug|Any CPU.Build.0 = Debug|Any CPU
 		{5D15AD79-050C-4780-986E-0F1138EA1D40}.Debug|x64.ActiveCfg = Debug|Any CPU
 		{5D15AD79-050C-4780-986E-0F1138EA1D40}.Debug|x64.Build.0 = Debug|Any CPU
 		{5D15AD79-050C-4780-986E-0F1138EA1D40}.Release|Any CPU.ActiveCfg = Release|Any CPU
 		{5D15AD79-050C-4780-986E-0F1138EA1D40}.Release|Any CPU.Build.0 = Release|Any CPU
-		{5D15AD79-050C-4780-986E-0F1138EA1D40}.Release|x64.ActiveCfg = Release|x64
-		{5D15AD79-050C-4780-986E-0F1138EA1D40}.Release|x64.Build.0 = Release|x64
+		{5D15AD79-050C-4780-986E-0F1138EA1D40}.Release|x64.ActiveCfg = Release|Any CPU
+		{5D15AD79-050C-4780-986E-0F1138EA1D40}.Release|x64.Build.0 = Release|Any CPU
 		{82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
 		{82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Debug|Any CPU.Build.0 = Debug|Any CPU
 		{82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Debug|x64.ActiveCfg = Debug|Any CPU
 		{82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Debug|x64.Build.0 = Debug|Any CPU
 		{82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Release|Any CPU.ActiveCfg = Release|Any CPU
 		{82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Release|Any CPU.Build.0 = Release|Any CPU
-		{82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Release|x64.ActiveCfg = Release|x64
-		{82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Release|x64.Build.0 = Release|x64
+		{82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Release|x64.ActiveCfg = Release|Any CPU
+		{82B1D288-51A6-411F-A5F9-E37C6A72E7DA}.Release|x64.Build.0 = Release|Any CPU
 		{F826ED1A-187A-484F-ABE4-D794E5CE0F50}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
 		{F826ED1A-187A-484F-ABE4-D794E5CE0F50}.Debug|Any CPU.Build.0 = Debug|Any CPU
 		{F826ED1A-187A-484F-ABE4-D794E5CE0F50}.Debug|x64.ActiveCfg = Debug|Any CPU
```

**Comment by quisquous** [comment]
> Those paths look like they're from a pretty old `FFXIVClientStructs` build, the correct paths should be at `OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Base\Global...` and `OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Transformed\Global...` You might want to double check that folder structure?

Ah, I see. This is an old path on disk.

> For reference, the `FFXIVClientStructs` output directory changed as part of #180. This wasn't causing an issue before because the include path for `.cs` files were explicitly defined, but with the new project structure all `.cs` files are included by default and need to be explicitly excluded:

Yeah, that's exactly it.

**Comment by quisquous** [comment]
> This could use some additional testing (namely testing the actual built artifact by simulating the update process and testing in other languages), but I wanted to throw it up here for initial feedback.

Initial smoke testing by applying the built artifact over top of the existing directory structure seems good to me. I didn't do much other than hit a striking dummy and check the console output and the double check some OP-specific logs.

I'll probably just keep running with it and will let you know if somehow (unlikely) anything comes up.

**Comment by valarnin** [comment]
> Solution changes were not enough. I needed these additional changes to have Visual Studio stop complaining. (This is mostly the same as my previous diff, but not entirely.)

Really odd that my VS (VS 2019) isn't complaining about this but yours is. I think we should probably figure that out before this can be considered good?

**Comment by quisquous** [comment]
> Really odd that my VS (VS 2019) isn't complaining about this but yours is. I think we should probably figure that out before this can be considered good?

This is VS 2022 over here, which I suspect is the difference.

**Comment by valarnin** [comment]
I had to switch off of the `Release`/`Any CPU` selection in VS and switch back to get it to complain about this properly for some reason, at which point it generated the same diff as you posted. Just VS being weird I guess 🤷 

As for language testing, it's just making sure that OP properly displays the localized form values for e.g. French on e.g. the `General Settings` tab. I'm not currently set up to run anything in any locale other than system default.

**Review by quisquous — APPROVED** [review]

**Pull request merged**
