### PR TITLE
Version bump to 0.19.38

### PR DESCRIPTION
**Pull request by xiashtra**
CN Dawntrail bump per discussion on #399.  @MnFeN @ShadyWhite @Ra-Workspace please version bump when needed for CN or KR, most of us don't have any visibility to what's going on with the non-international release schedule.

### CODE REVIEW

**Comment by valarnin** [comment]
Maybe we need a github action that looks for changes to the version maps in FFXIVMemory.cs and comments that a follow up PR to version bump may be needed?

**Review by valarnin — APPROVED** [review]

**Comment by xiashtra** [comment]
> Maybe we need a github action that looks for changes to the version maps in FFXIVMemory.cs and comments that a follow up PR to version bump may be needed?

That's a good idea; if something is touched that normally needs a version bump, warn on PR submission or possibly even auto-generate one on merge.

**Comment by valarnin** [comment]
I'm not sure about auto-generating a PR, since many times a version bump isn't needed. In this case it was because there was still a match for the signature that was being scanned, but many times that's not the case.

**Comment by Ra-Workspace** [comment]
The patch date for KR server will be announced at the fan fest a week later.

**Pull request merged**
