### PR TITLE
Add editorconfig and lint check workflow

### PR DESCRIPTION
**Pull request by valarnin**
Setting EOL to `CRLF` showed 19827 lines that would need to be changed.
Setting EOL to `LF` showed only 2338 lines that need to be changed.

I opted to generate the editorconfig with VS first, then comment out all the generated rules, then add the EOL rule. This should allow us to enable/disable the "recommended"/generated rules one at a time.

I expect and hope that this will trigger the workflow and error on PR, at which point I'll correct the line endings with `dotnet format` and that should allow it to pass.

### CODE REVIEW

**Comment by quisquous** [comment]
Not that these other formatting changes are bad, but there's definitely a few more than line endings.

**Comment by valarnin** [comment]
> Not that these other formatting changes are bad, but there's definitely a few more than line endings.

I wasn't able to prevent them regardless of any other editorconfig settings, unfortunately. They seem to be built-in defaults for the `dotnet format` command as far as I can tell.

**Comment by quisquous** [comment]
> > Not that these other formatting changes are bad, but there's definitely a few more than line endings.
> 
> I wasn't able to prevent them regardless of any other editorconfig settings, unfortunately. They seem to be built-in defaults for the `dotnet format` command as far as I can tell.

They seem like good changes and fairly minimal, so seems fine enough to me.

**Comment by valarnin** [comment]
This would be ready for merging except that for some reason `dotnet format --verify-no-changes` produces different results in github workflow than it does locally.

**Comment by valarnin** [comment]
That's success it looks like, was just missing `.gitattributes` I guess.

**Review by quisquous — APPROVED** [review]
Based on the comments in #11, it doesn't sound like anybody really cares strongly about formatting one way or the other, other than just have it be automatic.  Picking rules that are consistent with the bulk of the code makes sense to me.  So, I think this seems fine to me to go ahead and merge.

**Comment by quisquous** [comment]
(Also, thank you! Yay automation!!)

**Comment by trim21** [comment]
I encounter a problem after this commit, git always show some files are changed but I can't reset them to head.

I have a git config with `autocrlf = false`

```diff
warning: in the working copy of 'HtmlRenderer/OverlayForm.resx', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'HtmlRenderer/Resources.Designer.cs', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/Controls/GeneralConfigTab.Designer.cs', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/Controls/GeneralConfigTab.resx', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/EventSources/BuiltinEventConfigPanel.Designer.cs', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/EventSources/BuiltinEventConfigPanel.resx', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/Overlays/MiniParseConfigPanel.Designer.cs', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/Overlays/MiniParseConfigPanel.ja-JP.resx', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/Overlays/MiniParseConfigPanel.resx', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/Resources.Designer.cs', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/app.config', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/resources/enmity/css/handle.png', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/resources/enmity/js/aggrolist.js', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/resources/enmity/js/enmity.js', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/resources/enmity/js/funcs.js', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/resources/enmity/js/targetinfo.js', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/resources/enmity_target_funcs.js', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/resources/handle.png', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/resources/targetbars/focus_target.html', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/resources/targetbars/hover_target.html', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/resources/targetbars/target.html', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/resources/targetbars/target_of_target.html', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/resources/targetbars/targetbars.css', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Core/resources/targetbars/targetbars.js', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Updater/Resources.Designer.cs', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.Updater/Resources.resx', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin.sln', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin/Resources.Designer.cs', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'OverlayPlugin/app.config', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'docs/assets/handle.png', CRLF will be replaced by LF the next time Git touches it
diff --git a/HtmlRenderer/OverlayForm.resx b/HtmlRenderer/OverlayForm.resx
index 29dcb1b..1af7de1 100644
--- a/HtmlRenderer/OverlayForm.resx
+++ b/HtmlRenderer/OverlayForm.resx
@@ -1,120 +1,120 @@
```

**Comment by trim21** [comment]
> Setting EOL to LF showed only 2338 lines that need to be changed.

I run dox2unix on all files, and there are still these changed:

```shell
$ git commit -m 'dos2unix'
[main 6bab870] dos2unix
 210 files changed, 7576 insertions(+), 7576 deletions(-)
```

**Comment by trim21** [comment]
And ever worse, some binary files are affected by this:

```text
warning: CRLF will be replaced by LF in docs/assets/handle.png.
The file will have its original line endings in your working directory
diff --git a/docs/assets/handle.png b/docs/assets/handle.png
index e8a9a3a..1c5f29f 100644
Binary files a/docs/assets/handle.png and b/docs/assets/handle.png differ
```

**Comment by valarnin** [comment]
Hmm, try adjusting .gitattributes to:
```
*.cs text eol=lf
*.csproj text eol=lf
```

And see if that works and doesn't break the workflow server-side?

**Comment by trim21** [comment]
ci works fine https://github.com/trim21/OverlayPlugin/actions/runs/3212497608/jobs/5251416369

**Comment by trim21** [comment]
I know what's going wrong, you set all files' EOL to lf in attributes but actually you only changed `**.cs` files in this PR.

**Comment by trim21** [comment]
yes in https://github.com/OverlayPlugin/OverlayPlugin/pull/113

**Pull request merged**
