### PR TITLE
HiDPI fixes for tab control

### LINKED ISSUE #352: Minor UI element sizing issues when running in custom DPI scaling
I'm trying to make ACT behave better when using non-100% DPI scaling and I'm currently reviewing various plugins to see if there are any issues that could be fixed.  The main thing that I am seeing is the page selection on the left-side of the UI.  It seems to resist the size adjustments that Windows tries to apply automatically to all controls and fonts.

image 
image 
image

These screenshots were taken with the new version of ACT(that has better scaling), but the current version of ACT has OverlayPlugin's UI also behave this way.  The width of the outer control seems to be fixed and the height of each individual selector seems fixed as well.  Windows rescales the font size to how it thinks it should, but with that resizing... the text has trouble fitting.

My observations so far are that native controls placed in Visual Studio or even UserControls inserted programmatically will get rescaled properly by Windows.  However controls created and sized in C# code will be taken literally and Windows will not rescale them.  It might have to do with SuspendLayout and ResumeLayout that InitializeComponent uses that makes it work for Visual Studio.

I'll have to browse through the code here to know for sure, but my guess is that these page selection "buttons" are sized with C# code after initialization.  You don't necessarily have to convert them to UserControls since these are pretty simple looking controls... but you'll need a way to know what size to make them.  Unfortunately the Microsoft provided methods of detecting DPI are pretty useless and don't even agree with each other.  `Control.DeviceDpi` always said 100% and several pinvoke methods also failed to give a proper result.  I gave up before trying other methods that rely on later OS versions which would make ACT incompatible with older Windows OSes for no reason.  ACT *will have* a `FormActMain.DpiScale` property, but that won't help you right this second.  That was made with a hidden Panel that's just 96x96 and will get resized automatically by Windows.  You could do this as well to get the current DPI of your UI.

### PR DESCRIPTION
**Pull request by EQAditu**
Fixes #352 

I can't think of anything else I need to do with the DPI changes part.  The only thing that bothers me is that at 100% DPI, the top border is one pixel different compared to the side borders.  150% & 200% scaling has the same borders all around, though.

Please understand that this relies on a newer version of ACT to detect DPI scaling in a reliable manner.  For this reason, please hold off on releasing the changes in this PR until you feel it is likely that everyone has updated ACT to one of the new releases of this year.  It may create a problem if a long-absent player comes back and updates OverlayPlugin and restarts while ignoring the ACT update also available.  The effect is that this tab control will fail to render unless ACT is updated.

### CODE REVIEW

**Comment by valarnin** [comment]
Would it be worth it to just access the property via reflection for now with a fallback to `1` for DPI scale, then later down the line when we're confident that the vast majority of players have updated we can bump the linked version and access it directly?

**Comment by EQAditu** [comment]
I considered it, but since it wasn't causing a real crash I didn't explore it further.  I did ask that question in the original issue.

From my memory, the effect is that the base plugin will load but will not be able to instantiate the TabControlExt class inside of Core without a sufficient version of ACT.  I think this displays an error in ACT's plugin tab label and the upper part of OverlayPlugin's tab will be blank.  I think the log window still shows.

I gave the warning to be aware of it.  But there's always a chance that other people's machines will show the effect I described differently.  It would be useful for anyone reading this to see if it is worse for them than what I have described.

**Comment by EQAditu** [comment]
Oh, I had a question about DEPS.json that I was curious about when setting up the environment.  Is it possible to add a file entry without a hash?  I was thinking it would be useful to place `https://advancedcombattracker.com/apidoc/Advanced%20Combat%20Tracker.XML` in ACT's folder for Visual Studio Intellisense... but this file updates as necessary and I don't host outdated versions to make it static.

**Comment by EQAditu** [comment]
I tried running the new OP with the old ACT again and it's not as bad as I remember.  Maybe the release version of ACT with no Visual Studio made the difference.

You will not get any errors or bad effects until you click on the **OverlayPlugin.dll** tab and see this:
image

Now that Windows Defender is no longer flagging the latest ACT update, I'm less worried about this.

**Review by valarnin — APPROVED** [review]

**Pull request merged**
