### PR TITLE
Visual Studio fetch_deps and strip-clientstructs support

### PR DESCRIPTION
**Pull request by valarnin**
~~This is based on the other two powershell PRs. Only commits starting with 3834c31be3a0dfbd465e3ae4dc237fabaeaf6250 (one at the time of this PR being created) are part of this PR. I will rebase to `main` when the dependent PRs are merged.~~

Rebased after parent PRs were merged.

The logic here is pretty simple:
1. Create a dummy `VSBuildDeps` project
2. Have that project require `Newtonsoft.Json` for dependency reasons
3. Have that project run the associated powershell scripts
4. Require that project as a `ProjectReference` wherever we're using a dependency that's loaded via `fetch_deps.ps1`

Outstanding thoughts/TODOs:
1. ~~Should we make the two powershell scripts exist as part of this project so they're easily visible in VS?~~
2. ~~Somehow stop this from generating a pointless dll file~~

### CODE REVIEW

**Comment by quisquous** [comment]
> Should we make the two powershell scripts exist as part of this project so they're easily visible in VS?

Yeah, I think that would make sense.

> Somehow stop this from generating a pointless dll file

This is definitely a bit weird, but seems like a "could clean this up later" sort of issue.

**Comment by valarnin** [comment]
Pending testing from others to make sure this works as expected in other environments, I think this is ready for review/merge.

**Comment by quisquous** [comment]
I think there is a missing dependency somewhere.

I opened the project in Visual Studio. (It seemed to be on Release/x64, not that I think this is important.) I built VSBuildDeps on its own. I did a rebuild all on the full project, and got this error:

```
1>==> Stripping FFXIVClientStructs for namespace Global...
1>C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Base\Global\FFXIVClientStructs\CExportIgnore.cs
1>Unhandled exception. System.IO.IOException: The process cannot access the file 'C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Core\Thirdparty\FFXIVClientStructs\Transformed\Global\FFXIVClientStructs\CExportIgnore.cs' because it is being used by another process.
1>   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
1>   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
1>   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
1>   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
1>   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
1>   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
1>   at System.IO.File.WriteAllText(String path, String contents)
1>   at StripFFXIVClientStructs.StripFFXIVClientStructs.Main(String[] args) in C:\Users\enne\OverlayPlugin.ngld\tools\StripFFXIVClientStructs\StripFFXIVClientStructs\StripFFXIVClientStructs.cs:line 211
```

After that I tried another rebuild all which seemed to say that it was trying to do both VSBuildDeps and StripFFXIVClientStructs at the same time:
```
Rebuild started...
1>------ Rebuild All started: Project: VSBuildDeps, Configuration: Release Any CPU ------
2>------ Rebuild All started: Project: StripFFXIVClientStructs, Configuration: Release Any CPU ------
3>------ Rebuild All started: Project: HtmlRenderer, Configuration: Release Any CPU ------
Restored C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Common\OverlayPlugin.Common.csproj (in 11 ms).
Restored C:\Users\enne\OverlayPlugin.ngld\HtmlRenderer\HtmlRenderer.csproj (in 78 ms).
Restored C:\Users\enne\OverlayPlugin.ngld\AddonExample\AddonExample.csproj (in 84 ms).
Restored C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Core\OverlayPlugin.Core.csproj (in 82 ms).
Restored C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin.Updater\OverlayPlugin.Updater.csproj (in 84 ms).
Restored C:\Users\enne\OverlayPlugin.ngld\tools\VSBuildDeps\VSBuildDeps.csproj (in 11 ms).
Restored C:\Users\enne\OverlayPlugin.ngld\OverlayPlugin\OverlayPlugin.csproj (in 7 ms).
Restored C:\Users\enne\OverlayPlugin.ngld\tools\StripFFXIVClientStructs\StripFFXIVClientStructs\StripFFXIVClientStructs.csproj (in 86 ms).
2>D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5652,5): warning MSB3061: Unable to delete file "C:\Users\enne\OverlayPlugin.ngld\tools\StripFFXIVClientStructs\StripFFXIVClientStructs\bin\Release\StripFFXIVClientStructs.exe". Access to the path 'C:\Users\enne\OverlayPlugin.ngld\tools\StripFFXIVClientStructs\StripFFXIVClientStructs\bin\Release\StripFFXIVClientStructs.exe' is denied.
2>D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5652,5): warning MSB3061: Unable to delete file "C:\Users\enne\OverlayPlugin.ngld\tools\StripFFXIVClientStructs\StripFFXIVClientStructs\bin\Release\StripFFXIVClientStructs.dll". Access to the path 'C:\Users\enne\OverlayPlugin.ngld\tools\StripFFXIVClientStructs\StripFFXIVClientStructs\bin\Release\StripFFXIVClientStructs.dll' is denied.
2>D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5652,5): warning MSB3061: Unable to delete file "C:\Users\enne\OverlayPlugin.ngld\tools\StripFFXIVClientStructs\StripFFXIVClientStructs\bin\Release\StripFFXIVClientStructs.pdb". Access to the path 'C:\Users\enne\OverlayPlugin.ngld\tools\StripFFXIVClientStructs\StripFFXIVClientStructs\bin\Release\StripFFXIVClientStructs.pdb' is denied.
2>D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5652,5): warning MSB3061: Unable to delete file "C:\Users\enne\OverlayPlugin.ngld\tools\StripFFXIVClientStructs\StripFFXIVClientStructs\bin\Release\Microsoft.CodeAnalysis.dll". Access to the path 'C:\Users\enne\OverlayPlugin.ngld\tools\StripFFXIVClientStructs\StripFFXIVClientStructs\bin\Release\Microsoft.CodeAnalysis.dll' is denied.
2>D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5652,5): warning MSB3061: Unable to delete file "C:\Users\enne\OverlayPlugin.ngld\tools\StripFFXIVClientStructs\StripFFXIVClientStructs\bin\Release\Microsoft.CodeAnalysis.CSharp.dll". Access to the path 'C:\Users\enne\OverlayPlugin.ngld\tools\StripFFXIVClientStructs\StripFFXIVClientStructs\bin\Release\Microsoft.CodeAnalysis.CSharp.dll' is denied.
2>D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5652,5): warning MSB3061: Unable to delete file "C:\Users\enne\OverlayPlugin.ngld\tools\StripFFXIVClientStructs\StripFFXIVClientStructs\bin\Release\System.Collections.Immutable.dll". Access to the path 'C:\Users\enne\OverlayPlugin.ngld\tools\StripFFXIVClientStructs\StripFFXIVClientStructs\bin\Release\System.Collections.Immutable.dll' is denied.
2>D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5652,5): warning MSB3061: Unable to delete file "C:\Users\enne\OverlayPlugin.ngld\tools\StripFFXIVClientStructs\StripFFXIVClientStructs\bin\Release\System.Reflection.Metadata.dll". Access to the path 'C:\Users\enne\OverlayPlugin.ngld\tools\StripFFXIVClientStructs\StripFFXIVClientStructs\bin\Release\System.Reflection.Metadata.dll' is denied.
3>HtmlRenderer -> C:\Users\enne\OverlayPlugin.ngld\out\Release\libs\HtmlRenderer.dll
2>D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5150,5): warning MSB3026: Could not copy "C:\Users\enne\OverlayPlugin.ngld\tools\StripFFXIVClientStructs\StripFFXIVClientStructs\obj\Release\apphost.exe" to "bin\Release\StripFFXIVClientStructs.exe". Beginning retry 1 in 1000ms. The process cannot access the file 'bin\Release\StripFFXIVClientStructs.exe' because it is being used by another process. The file is locked by: "StripFFXIVClientStructs.exe (31152)"
1>Saving dependency cache...
1>Cleaning up...
1>==> Preparing FFXIVClientStructs...
1>==> Building StripFFXIVClientStructs...
1>MSBuild version 17.4.1+9a89d02ff for .NET
2>D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5150,5): warning MSB3026: Could not copy "C:\Users\enne\OverlayPlugin.ngld\tools\StripFFXIVClientStructs\StripFFXIVClientStructs\obj\Release\apphost.exe" to "bin\Release\StripFFXIVClientStructs.exe". Beginning retry 2 in 1000ms. The process cannot access the file 'bin\Release\StripFFXIVClientStructs.exe' because it is being used by another process. The file is locked by: "StripFFXIVClientStructs.exe (31152)"
```

I think probably VSBuildDeps should depend on StripFFXIVClientStructs rather than building it directly to avoid this conflict.

**Comment by valarnin** [comment]
> I think probably VSBuildDeps should depend on StripFFXIVClientStructs rather than building it directly to avoid this conflict.

The only problem with this is that right now we force build the Release/x64 version of StripFFXIVClientStructs and reference that directly in the powershell script that invokes it. We'd need to maybe detect the built version of StripFFXIVClientStructs or maybe pass in the info via optional arguments to the script?

**Comment by quisquous** [comment]
Yeah, I'm not sure what the right answer is. At the very least, something needs to be done so the two don't build in parallel.

You could put the client structs project in its own solution file and build it from the deps project. You could have the client structs executable depend on the deps project (weird, but maybe workable). Maybe there's some way to have the deps project depend on a specific version of the client structs executable, but I don't know of one. Or, you could have the deps script look for various executables in different paths depending on config? I think any of these options are plausible.

**Comment by quisquous** [comment]
> Hopefully the most recent commit fixes the build for you? I think the parallel build thing is something VS2022 is doing, because I tried about 10 times and couldn't reproduce the issue from any build state (fresh, partial, csproj files changed, or completed) on VS2019.

The changes look reasonable (although minorly I think the script could probably just not build at all rather than have two paths, but maybe that makes your workflow easier?). I haven't had a chance to test it yet, but I do see there's some build issues on ci.

I think the setting is Options -> Projects and Solutions -> Build And Run -> maximum number of parallel project builds which the internet suggests exists on earlier visual studios as well, but I can't prove.

**Comment by valarnin** [comment]
I've sent a general request for review to the maintainers role. I'm not sure who is interested in co-reviewing PRs here.

**Comment by valarnin** [comment]
I'm going to go ahead and force merge this PR, since quisquous had already done some review and feedback which has been addressed.

**Pull request merged**
