### PR TITLE
Add cast target location for location-targeted abilities

### PR DESCRIPTION
**Pull request by valarnin**
This PR adds the ground target location for actor casts to `getCombatants` calls and `CombatantMemory` lines. This is testable by players via entering a dungeon in explorer mode as a caster and using LB, or by using normal ground-targetted abilities that have a cast time such as Ifrit eruptions/puddles.

Also remove CombatantMemory61, CombatantMemory62, since CN/KR are on 6.3+ so these fields don't need to be added to those classes.

Only tested Global region offsets but these should never really change unless the entire cast info struct changes, at which point we'll need to figure out everything else again anyways. This is also in `aers/FFXIVClientStructs` so we can reference that if needed.

```cs
    public struct CastInfo {
        // ...
        [FieldOffset(0x20)] public Vector3 CastLocation;
    }
```

There might be a `CastGroundTargetHeading` following the fields like other x/y/z memory locations, but I wasn't able to find a player action that triggered it.

Picks up target locations for `Ifrit Hard` `Eruption` and `Radiant Plume` casts, for example.

```
20|2023-10-14T21:07:00.1800000-04:00|400025E6|Ifrit|54F|Radiant Plume|E0000000||2.700|36.00|0.00|-0.21|0.00|7f67899943465d08
...
261|2023-10-14T21:06:59.9810000-04:00|Change|400025E6|CastBuffID|1359|CastDurationCurrent|0.0072|CastDurationMax|2.7000|CastGroundTargetX|-20.0046|CastGroundTargetY|-0.0153|CastGroundTargetZ|-0.0153|IsCasting1|1|IsCasting2|1|f2d7a85d31cf4bdf
...
21|2023-10-14T21:07:03.1680000-04:00|400025E6|Ifrit|54F|Radiant Plume|E0000000||0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|||||||||||2589|2589|0|10000|||36.00|0.00|-0.21|0.00|0000102D|0|0|a6aa09b55835d4c9
...
261|2023-10-14T21:07:02.8270000-04:00|Change|400025E6|CastBuffID|0|CastDurationCurrent|0.0000|CastDurationMax|0.0000|IsCasting1|0|IsCasting2|0|9e8f4de965391239
```

```
20|2023-10-14T21:07:16.8720000-04:00|400025E9|Ifrit|54E|Eruption|E0000000||2.700|36.00|-0.02|-0.20|-0.75|09604bd17d0d6488
261|2023-10-14T21:07:16.3830000-04:00|Change|400025E9|CastBuffID|1358|CastDurationCurrent|0.0078|CastDurationMax|2.7000|CastGroundTargetX|11.3984|CastGroundTargetY|9.6895|Heading|-0.7580|IsCasting1|1|IsCasting2|1|9242388d90029366
```

Note that the game does not zero out these memory locations between casts unless an ability targeted on an entity was used, so we may want to always send all three if one changes like we do with `PosX`/`PosY`/`PosZ`/`Heading` in the case that the actor using the ability's last ability use was at the same location.

### CODE REVIEW

**Comment by quisquous** [comment]
This looks reasonable to me overall. My only thoughts here are:
* it's nice that this exists in client structs
* agree with send x/y/z/heading (if we can fix heading) if any change
* what are the initial values here? do we need to explicitly handle not sending whatever memory on the add message?
* do you think heading exists on charge-like mechanics? rokkon shishui revel charges seem like one possibility
* I also wonder if this would solve my TODOs in the variant rokkon seasons of X and soldiers of death

**Comment by valarnin** [comment]
> * agree with send x/y/z/heading (if we can fix heading) if any change

👍 

> * what are the initial values here? do we need to explicitly handle not sending whatever memory on the add message?

Hmm, default values seem to vary so I don't think this part of the struct is being `0`'d out on add. Maybe these values should only be considered/sent if `IsCasting1 == 1`?

> * do you think heading exists on charge-like mechanics? rokkon shishui revel charges seem like one possibility

I forget, are these in the variant version? If so, I can do a quick run with the potential `Heading` added and see if it makes sense. I don't remember what path this is even down tbh.

> * I also wonder if this would solve my TODOs in the variant rokkon seasons of X and soldiers of death

Maybe? Again, I could do a run solo with these changes and DM you the log so you can check, but I don't remember what paths lead to where.

**Comment by xpdota** [comment]
Probably too complicated, but I wonder if there's a way to get this integrated into the StartsCasting line (or a custom equivalent of such). I'd imagine it probably has issues with the memory not being updated by the time the packet is processed.

**Comment by quisquous** [comment]
> > * what are the initial values here? do we need to explicitly handle not sending whatever memory on the add message?
> 
> Hmm, default values seem to vary so I don't think this part of the struct is being `0`'d out on add. Maybe these values should only be considered/sent if `IsCasting1 == 1`?

Yeah, I think that'd be reasonable.

> > * do you think heading exists on charge-like mechanics? rokkon shishui revel charges seem like one possibility
> 
> I forget, are these in the variant version? If so, I can do a quick run with the potential `Heading` added and see if it makes sense. I don't remember what path this is even down tbh.

Yeah, it's 8/9/10/11 paths by going right. It's the second boss. He drops big red lines (1 2 or 3) that are not always in the same direction.

> > * I also wonder if this would solve my TODOs in the variant rokkon seasons of X and soldiers of death
> 
> Maybe? Again, I could do a run solo with these changes and DM you the log so you can check, but I don't remember what paths lead to where.

Seasons of X are on any path. The soldiers of death are any left path. This is not worth your time to do, I can go check this myself, but mostly curious.

**Comment by xpdota** [comment]
If you want to be able to check the offset for cast heading (or re-check after an update) quickly, there's several BLU spells that should work (# 2, # 3, etc). I confirmed that they send the header in the packet, so it should end up in the combatant struct as well.

**Comment by valarnin** [comment]
> If you want to be able to check the offset for cast heading (or re-check after an update) quickly, there's several BLU spells that should work (# 2, # 3, etc). I confirmed that they send the header in the packet, so it should end up in the combatant struct as well.

I was doing all my testing by using caster and phys ranged limit break in an explorer mode dungeon. Caster LB3 obviously doesn't have it, but does phys ranged have a heading in the packet? If so, then it's either not conveyed in the struct or it's stored elsewhere.

**Comment by xpdota** [comment]
> I was doing all my testing by using caster and phys ranged limit break in an explorer mode dungeon. Caster LB3 obviously doesn't have it, but does phys ranged have a heading in the packet? If so, then it's either not conveyed in the struct or it's stored elsewhere.

I would assume ranged LB doesn't have it because it must be targeted on a unit. My understanding is that the different targeting types (nothing, unit, location, heading) are mutually exclusive. You need something like the BLU spells that can target a direction without needing a target unit (bomb toss is also a convenient way to test location targeting).

**Comment by valarnin** [comment]
I removed the change detection for combatant memory lines from this PR. I think there's still value to having this information available from `CombatantMemory` lines and `getCombatants` calls, so I think this is still worth merging.

**Review by quisquous — APPROVED** [review]

**Pull request merged**
