### PR TITLE
Add network log line for fate control information

### PR DESCRIPTION
**Pull request by valarnin**
Some code/logic pulled from https://github.com/quisquous/cactbot/blob/main/plugin/CactbotEventSource/FateWatcher.cs

Depends on #51 for now, since that PR has the groundwork for additional log lines on the OP side. As such, only the commit(s) starting with `Add network log line for fate control information` ([here](https://github.com/OverlayPlugin/OverlayPlugin/commit/5e01443f49a6d30771496c14e51de6dbf3cae84c) until I need to rebase to main after #51 is merged) are relevant.

Examples:

```
258|2022-09-16T22:40:58.6325655-04:00|Add|F0DF|000001F3|00000000|00000000|00000000|00000000|00000000|00000000|68145aa82eda3487
258|2022-09-16T22:40:49.1684933-04:00|Remove|046C|000001DB|00000000|00000000|00000000|00000000|00000000|00007F69|548153581733055d
258|2022-09-16T22:40:49.9944946-04:00|Update|F0DF|000001F0|00000000|00000000|00000000|00000000|00000000|00007F69|4fcac1c21e740f77
```

I figured mapping the control code to a textual status would be better here in case they change in the future, though I'm not sure exactly how often they change.

### CODE REVIEW

**Comment by valarnin** [comment]
This has been rebased to `main` and is ready for review.

**Comment by quisquous** [comment]
I think my only concern here (and same with the CE patch) is how often these update.  Is there one line per percentage change? More?  I'm not sure what all the other data is and how often it updates.

I think overall this is probably my main concern with extra lines overall, is how many lines does it create.  I mostly don't want to spam the log with a ton of extra lines if it's unnecessary.

**Comment by valarnin** [comment]
Roughly 5 minutes of fate lines. I couldn't find a zone with a lot of activity but this should still be fairly indicative of the rate of log line generation.

[Fate Lines.log](https://github.com/OverlayPlugin/OverlayPlugin/files/9594929/Fate.Lines.log)

**Comment by quisquous** [comment]
Yeah, that doesn't seem too bad for two fates.  It looks like 1 line/~1.5 seconds/fate to me, with some unnecessary duplication:

```
258|2022-09-18T13:42:27.3577698-04:00|Update|203A|00000702|00000010|00000000|00000000|00000000|00000000|6E756F63|39f4748423f4f704
258|2022-09-18T13:42:28.6776822-04:00|Update|203A|00000702|00000010|00000000|00000000|00000000|00000000|6E756F63|cfe94c3820f92786
258|2022-09-18T13:42:30.0387419-04:00|Update|203A|00000702|00000010|00000000|00000000|00000000|00000000|6E756F63|f680631c890da8a8
```

I was wondering a little if it made sense to cache progress and only send when the value changed, but that's maybe overkill.

**Review by quisquous — APPROVED** [review]

**Pull request merged**
