### PR TITLE
Add CombatantMemory65 for 6.5 global update

### PR DESCRIPTION
**Pull request by valarnin**
Cursory check of the values is correct. I did not check `WeaponId`, the new offset was calculated based on old offsets, so if someone else could check that I would appreciate it.

Also updated the comments on `MonsterType`/`AggressionStatus`.

Also also updated the comment on `NameBytes`.

### CODE REVIEW

**Comment by valarnin** [comment]
`WeaponId` is definitely wrong, but I'm not in a position right now to track it down manually.

**Comment by quisquous** [comment]
Do we have any good content to go look it up in easily? I forget what the way to test this is.

**Comment by quisquous** [comment]
Also, I'm fine with doing an OP release right now and making a note of this, but probably there will be complaints about TOP if this doesn't get fixed sooner rather than later.

**Comment by valarnin** [comment]
> Do we have any good content to go look it up in easily? I forget what the way to test this is.

Omega M&F from Stormblood raids, or P12N angels should have WeaponId change from `0` to `4` sometime during the LC chargeup IIRC.

> Also, I'm fine with doing an OP release right now and making a note of this, but probably there will be complaints about TOP if this doesn't get fixed sooner rather than later.

I'm also concerned that this might cause issues with xp's TriggEvent triggers, I'm not sure what all they're using `WeaponId` for over there.

I won't have time for likely the rest of the night to look into this issue though.

**Comment by quisquous** [comment]
I'll see if I can find time, but I won't have much. I still think fixing most of it is worth releasing.

**Comment by valarnin** [comment]
Maybe we can push this out with a big bold notice that cactbot TOP triggers aren't fixed or something?

**Comment by quisquous** [comment]
Yeah, that was exactly my thought, not that anybody but Techno reads the release notes.

**Comment by xpdota** [comment]
I am also only using them for TOP at the moment. What I would suggest for the time being is to have a specific nonsense value (like -1) as a way of saying "this isn't working". I put logic in my triggers to not blow up or give wrong calls if someone was using an old OP version that didn't have WeaponId, and -1 was the fake value I chose for this if the field was missing entirely from the OP response.

**Comment by valarnin** [comment]
99% sure I found it at `0xC30`, just confirming in a few fights. Once I know it's right I'll document the most consistent way to find it next time.

**Comment by valarnin** [comment]
Confirmed. To track this down in the future:

1. Enter O12N
2. Snapshot boss's (`Omega-M`) memory before pull
3. Immediately after boss uses `Synthetic Shield`, snapshot memory again
4. Check for bytes that changed from `0x00` to `0x04`
5. After `Superfluid` status effect is applied, `TransformationId` is `0xC8` and `WeaponId` is `0x06`, snapshot again if needed
6. During `Electric Slide`, `WeaponId` is `0x0B`, this should be enough to narrow it down fully regardless of any other factors.

Obviously this can be done with CE as well if that's easier for you, find boss memory location, limit search to that struct area, search for `0` first, then `4` after shield, then `6` after superfluid, then `11` during electric slide.

**Pull request merged**
