### PR TITLE
Fix LineCombatant FP decimal separator being locale-dependent.

### LINKED ISSUE #221: CombatantMemory lines use localized decimal point
`261|2023-05-30T23:32:35.7820000+02:00|Change|10ABCDEF|Heading|-2,0746|PosX|124,5246|PosY|77,6094|PosZ|-0,0037|3968f45132ff9c4b`

Should always use `.` regardless of locale to stay consistent with the base XIV plugin.

### PR DESCRIPTION
**Pull request by xpdota**
Fixes #221 

This is not the only solution - another option is to set the whole thread's locale, I'm just not familiar enough with the threading model in C# to know the real impact of that.

### CODE REVIEW

**Comment by valarnin** [comment]
We can't set locale for the thread, because in some cases the calling thread is controlled by the thread pool upstream in `FFXIV_ACT_Plugin` and would therefore have impact on other plugins.

**Comment by xpdota** [comment]
> We can't set locale for the thread, because in some cases the calling thread is controlled by the thread pool upstream in `FFXIV_ACT_Plugin` and would therefore have impact on other plugins.

In that case, it will probably just have to be a "remember to check this if you add new field types" and be fixed individually.

**Comment by valarnin** [comment]
> In that case, it will probably just have to be a "remember to check this if you add new field types" and be fixed individually.

Alternatively, the format logic could be centralized somewhere and then invoked from here, since we're also manually formatting to get the 4 decimal places.

**Review by quisquous — APPROVED** [review]
Personally, I feel like this is fine for now and fixes a bug.  If we want to centralize formatting in some way to prevent bugs like this in the future, there's nothing here that prevents that.

**Pull request merged**
